Add member page
GSG-K3/360HMR pull request #36
Opened 2020-07-07 12:34 UTC by rubasider

in the client side 4 text fields were add to take the employee's data and then add this data to the database and i used sweet alert  to pop up messages in case of success or error
and there is a  file called SwitchRoute is used to switch between the endpoints 
to view the page use   /dashboard

2020-07-08 12:42 UTC, mantagen commented on server/controller/employee/getEmployees.js
> +// const getEmployeesBy = require('../../database/query/employee/getEmployees');
Why is this all commented out?

2020-07-08 12:42 UTC, mantagen commented on server/controller/employee/addNewEmployee.js
> +	const Empdata = req.body;
`employeeData`

- PascalCase is reserverd for classes in javascript (https://www.robinwieruch.de/javascript-naming-conventions)

2020-07-08 12:42 UTC, mantagen commented on client/src/Componants/dashboard/NewMember.jsx
> +		console.log('theData', TheData);
:fire:

2020-07-08 12:42 UTC, mantagen commented on client/src/Componants/dashboard/NewMember.jsx
> +	console.log('data', empData);
:fire:

2020-07-08 12:51 UTC, mantagen requested changes

2020-07-08 12:51 UTC, mantagen commented on package.json
> +		"@material-ui/core": "^4.11.0",
I think this should be in `client/package.json`?

2020-07-10 05:23 UTC, yaqootturman requested changes

2020-07-10 05:23 UTC, yaqootturman commented on client/src/App.js
> +import SwitchRoute from './Componants/base/SwitchRoute';
What is this path? did we talk about it? we talked about file structure and I don't think you mentioned this!

2020-07-10 05:23 UTC, yaqootturman commented on client/src/App.js
> +import SwitchRoute from './Componants/base/SwitchRoute';
and please note the components folder is smaller

2020-07-10 05:23 UTC, yaqootturman commented on client/src/Componants/dashboard/NewMember.jsx
> +const useStyles = makeStyles((theme) => ({
I don`t prefer using styling include jsx file

2020-07-10 05:47 UTC, yaqootturman commented on client/src/Componants/dashboard/NewMember.jsx
> +const useStyles = makeStyles((theme) => ({
add the template file, please!

2020-07-12 11:03 UTC, yaqootturman requested changes

2020-07-12 11:03 UTC, yaqootturman commented on package.json
> +		"sweetalert": "^2.1.2"
The sweetalert should not install here! , you should install it in client-side

2020-07-12 11:03 UTC, yaqootturman commented on client/src/App.js
> +			<Grid container>
Is there a reason to make router as a grid?

2020-07-12 11:03 UTC, yaqootturman commented on pull_request_template.md
> +* Adding button to confirm adding the employee.
Who should do this point?

2020-07-12 11:03 UTC, yaqootturman commented on server/controller/employee/addNewEmployee.js
> +			console.log('Error in post Employee : ', err);
delete console

2020-07-12 11:03 UTC, yaqootturman commented on server/controller/employee/addNewEmployee.js
> +	const employeeData = req.body;
I think you should make sure and validate the data before pass them to the query

2020-07-13 16:52 UTC, closed without merging