Add employee front end
GSG-K3/360HMR pull request #57
Opened 2020-07-14 17:51 UTC by rubasider

### What does this PR do?
Call the add new employee with http://localhost:3000/dashboard endpoint.

* On the dashBoard page you can add new employee  to the
  database after you add his name,email,date of hiring date and position.

*  button to confirm adding the employee.

- a pop up will appear to tell you if the process is done successfuly usin
  sweetalert.

### Does this Fix an Issue?

Fixes #56

### How to test this PR

- npm i

- cd client && npm i

- cd..

- npm run dev
- go to http://localhost:3000/dashboard endpoint

### Screenshots of changes
https://ibb.co/1fJgHrv

### Screenshots of changes

2020-07-15 07:09 UTC, yaqootturman requested changes

2020-07-15 07:09 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +		</Box>
I can`t read the code in this way! use formatting such as linting or prettier!!

2020-07-15 07:09 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +											<option aria-label="None" value="" />
Wondering why!

2020-07-15 07:09 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +										onChange={handleChange}
what if the user enters a name in email input, I mean not email formatting, should that be okay?

2020-07-15 12:59 UTC, yaqootturman submitted a review, later dismissed
Great work but I need you to document regular expressions!

2020-07-15 12:59 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +	const validateEmail = (email) => {
regular expressions! can you document this?

2020-07-16 10:33 UTC, karmelyoei submitted a review, later dismissed

2020-07-16 11:28 UTC, karmelyoei approved these changes

2020-07-16 14:51 UTC, mantagen commented
@rubasider you can paste image directly into PR description (you don't have use external website)

2020-07-16 14:55 UTC, mantagen reviewed
The styles look really good!!

Only one problem i have a problem when submitting the form:
![image](https://user-images.githubusercontent.com/12934669/87686829-e4664080-c77c-11ea-9c38-066e9e2931e4.png)
![image](https://user-images.githubusercontent.com/12934669/87686654-a832e000-c77c-11ea-9f81-c41922806c29.png)

2020-07-16 18:17 UTC, rubasider commented
> The styles look really good!!
> 
> Only one problem i have a problem when submitting the form:
> ![image](https://user-images.githubusercontent.com/12934669/87686829-e4664080-c77c-11ea-9c38-066e9e2931e4.png)
> ![image](https://user-images.githubusercontent.com/12934669/87686654-a832e000-c77c-11ea-9f81-c41922806c29.png)

2020-07-16 18:17 UTC, closed without merging