History front end
GSG-K3/360HMR pull request #63
Opened 2020-07-19 08:28 UTC by rubasider

Call the history with http://localhost:3000/dashboard/history endpoint.

on this page you can see a list of employees that have been reviewed before

Does this Fix an Issue? Fixes #41

How to test this PR npm i

cd client && npm i

cd..

npm run dev

go to http://localhost:3000/dashboard/history endpoint

Screenshots of changes if the database is empty you will only see a page loading
https://ibb.co/1v0qyT6

2020-07-19 08:49 UTC, yaqootturman requested changes

2020-07-19 08:49 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/HistoryStyle.jsx
> +	// textField: {
delete comments

2020-07-19 08:49 UTC, yaqootturman commented on client/src/components/LayoutComponents/Dashboard/NewMemberStyle.jsx
> +	form: {
Make it responsive!

2020-07-20 07:18 UTC, yaqootturman submitted a review, later dismissed

2020-07-20 09:41 UTC, mantagen requested changes

2020-07-20 09:41 UTC, mantagen commented on client/src/components/LayoutComponents/Dashboard/History.jsx
> +								{/* <Person color="disabled" fontSize="large" /> */}
:fire:

2020-07-20 09:41 UTC, mantagen commented on client/src/components/LayoutComponents/Dashboard/History.jsx
> +					{/* <Divider variant="fullWidth" component="li"
:fire_extinguisher:

2020-07-20 09:41 UTC, mantagen commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +			const TheData = {
`theData` (or just `data`) is fine

2020-07-20 09:41 UTC, mantagen commented on client/src/components/LayoutComponents/Dashboard/NewMember.jsx
> +											// position="end"
:eagle:

2020-07-20 09:41 UTC, mantagen commented on client/src/components/LayoutComponents/Dashboard/HistoryStyle.jsx
> +		display: 'flex',
Same as line 16

2020-07-21 07:41 UTC, yaqootturman submitted a review, later dismissed

2020-07-21 08:25 UTC, karmelyoei approved these changes

2020-07-21 14:14 UTC, yaqootturman approved these changes

2020-07-21 14:55 UTC, merged