History details
GSG-K3/360HMR pull request #68
Opened 2020-07-21 08:49 UTC by rubasider

### What does this PR do?

- Call the history details Page with http://localhost:3000/dashboard/history/:id
  endpoint.

on this page you can see a list of employees who reviewed the employee id above

using a query named getEmpById to get the reviewer name from database

use axios.get(/api/history/\${id}') you get the id from using useParams() to get
the result to the front end

LoaderProgress is used when the page take a time to load the result a loading
sign will show that the result is not ready yet and when it's ready the loading
will disapper and the page will view the result

### Does this Fix an Issue?

Fixes #64

### How to test this PR

- npm i

- cd client && npm i

- cd..

- npm run dev
- go to http://localhost:3000/dashboard/history/:id endpoint

### Screenshots of changes

https://ibb.co/m9nSqtc

2020-07-21 16:00 UTC, yaqootturman requested changes

2020-07-21 16:00 UTC, yaqootturman commented on server/database/queries/employees/getEmpById.js
> +			'select DISTINCT e.id employee_id,f.reviewer_name from employees e, forms f , employee_form ef where e.id=$1 AND ef.form_id=f.id;',
correct it to 
select DISTINCT e.id employee_id,f.reviewer_name from employees e, forms f , employee_form ef where e.id=$1 AND ef.form_id=f.id AND f.reviewer_name!= e.name;
so the employee name not appears again!

2020-07-21 16:00 UTC, yaqootturman commented on client/src/App.js
> +										path="/dashboard/history/:id"
prefer change it to be:  path="/dashboard/history/:id"

2020-07-21 16:00 UTC, yaqootturman commented on client/src/App.js
> +										path="/dashboard/history/:id/response/:name"
for the next page!

2020-07-22 07:50 UTC, yaqootturman approved these changes

2020-07-22 07:58 UTC, karmelyoei approved these changes

2020-07-22 08:03 UTC, merged